# Generated by Django 4.0.4 on 2022-07-25 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0002_fooditems'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FoodItems',
            new_name='FoodItem',
        ),
    ]
