# Generated by Django 4.0.4 on 2022-07-22 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApps', '0002_foodcategory_fc_craeted_at'),
        ('FoodApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50)),
                ('f_price', models.FloatField()),
                ('f_description', models.TextField()),
                ('f_secondary_description', models.TextField(default=True)),
                ('f_is_available', models.BooleanField(default=True)),
                ('f_photo', models.ImageField(upload_to='food_images/')),
                ('f_category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MyApps.foodcategory')),
            ],
        ),
        migrations.DeleteModel(
            name='FoodItems',
        ),
    ]
