# Generated by Django 4.0.4 on 2022-07-22 08:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MyApps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcategory',
            name='fc_craeted_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
